const fs = require('fs');

const keysToAdd = {
  "search_fav_placeholder": { id: "Cari judul buku favorit...", en: "Search favorite books..." },
  "fav_access_denied_title": { id: "Akses Ditolak", en: "Access Denied" },
  "fav_access_denied_desc": { id: "Silakan login terlebih dahulu untuk melihat koleksi favorit Anda.", en: "Please login to view your favorite collection." },
  "fav_empty_title": { id: "Rak Favorit Masih Sepi", en: "Favorite Shelf is Empty" },
  "fav_empty_desc": { id: "Kelihatannya belum ada buku yang berhasil mencuri hatimu. Yuk, kembali ke perpustakaan dan temukan bacaan seru pertamamu!", en: "It looks like no book has stolen your heart yet. Let's return to the library and find your first exciting read!" },
  "fav_empty_btn": { id: "Mulai Eksplorasi", en: "Start Exploring" },
  "fav_not_found": { id: "Tidak ada buku yang cocok dengan pencarian.", en: "No books match your search." },
  "fetch_error": { id: "Gagal memuat data dari server.", en: "Failed to load data from server." },

  "upload_placeholder_title": { id: "Contoh: Filosofi Teras", en: "Example: The Daily Stoic" },
  "upload_placeholder_author": { id: "Henry Manampiring", en: "Ryan Holiday" },
  "upload_placeholder_publisher": { id: "Gramedia", en: "Penguin" },
  "upload_placeholder_cover": { id: "Contoh: assets/thumb/book/dilan.jpeg", en: "Example: assets/thumb/book/dilan.jpeg" },
  "upload_placeholder_synopsis": { id: "Synopsis Buku...", en: "Book Synopsis..." },
  "upload_placeholder_story": { id: "Isi Cerita / Bab 1...", en: "Story Content / Chapter 1..." },
  "upload_warn_title_limit": { id: "Limit 100 karakter tercapai!", en: "100 characters limit reached!" },
  "upload_warn_author_limit": { id: "Limit 50 karakter tercapai!", en: "50 characters limit reached!" },
  "upload_form_stock": { id: "Stok Buku", en: "Stock" },
  "upload_cover_hint": { id: "Pilih jenis cover SVG atau pilih 'Ketik Path Internal' untuk gambar lokal.", en: "Select SVG cover type or choose 'Type Internal Path' for local image." },
  "upload_cover_hint_custom": { id: "Isi dengan lokasi gambar lokal. <strong>Klik kiri 2x</strong> pada input untuk kembali ke pilihan SVG.", en: "Fill with local image location. <strong>Double-click</strong> on input to return to SVG options." },
  "upload_preview_title": { id: "Live Preview Card", en: "Live Preview Card" },
  "upload_preview_default_title": { id: "Judul Buku", en: "Book Title" },
  "upload_preview_default_author": { id: "Nama Penulis", en: "Author Name" },
  "upload_genre_ph": { id: "Pilih Genre", en: "Select Genre" },
  "upload_cover_ph": { id: "Pilih Jenis Cover", en: "Select Cover Type" },
  "cover_opt_std": { id: "Buku Standar (SVG)", en: "Standard Book (SVG)" },
  "cover_opt_tech": { id: "Teknologi / Kode (SVG)", en: "Technology / Code (SVG)" },
  "cover_opt_people": { id: "Tokoh / Biografi (SVG)", en: "People / Biography (SVG)" },
  "cover_opt_globe": { id: "Dunia / Sejarah (SVG)", en: "Globe / History (SVG)" },
  "cover_opt_custom": { id: "Ketik Path Gambar Internal...", en: "Type Internal Image Path..." },
  "uploading_btn": { id: "Mengupload...", en: "Uploading..." },
  "upload_success": { id: "Buku berhasil diupload ke database!", en: "Book successfully uploaded to database!" },
  "upload_error": { id: "Gagal mengupload buku. Pastikan koneksi stabil.", en: "Failed to upload book. Ensure stable connection." },

  "genre_philosophy": { id: "Filsafat", en: "Philosophy" },
  "genre_politics": { id: "Politik", en: "Politics" },
  "genre_literature": { id: "Sastra", en: "Literature" },
  "genre_social": { id: "Sosial", en: "Social" },
  "genre_fiction": { id: "Fiksi", en: "Fiction" },
  "genre_biography": { id: "Biografi", en: "Biography" },
  "genre_technology": { id: "Teknologi", en: "Technology" },

  "admin_title": { id: "Admin Dashboard", en: "Admin Dashboard" },
  "admin_subtitle_graphs": { id: "Klik grafik untuk analisis mendalam per bulan/tahun.", en: "Click graphs for deep analysis per month/year." },
  "admin_total_books": { id: "TOTAL BUKU", en: "TOTAL BOOKS" },
  "admin_total_users": { id: "TOTAL MAHASISWA", en: "TOTAL STUDENTS" },
  "admin_total_activity": { id: "LOG AKTIVITAS", en: "ACTIVITY LOG" },
  "admin_trend_books": { id: "Tren Penambahan Buku", en: "Book Addition Trend" },
  "admin_trend_users": { id: "Pertumbuhan User", en: "User Growth" },
  "admin_trend_activity": { id: "Intensitas Aktivitas", en: "Activity Intensity" },
  "admin_traffic_borrow": { id: "Trafik Peminjaman Buku", en: "Borrow Traffic" },
  "admin_log_borrow": { id: "Log Peminjaman Buku", en: "Borrowing Log" },
  "admin_th_title": { id: "Judul Buku", en: "Book Title" },
  "admin_th_applicant": { id: "Pemohon", en: "Applicant" },
  "admin_th_time": { id: "Waktu", en: "Time" },
  "admin_th_status": { id: "Status", en: "Status" },
  "admin_collection_title": { id: "Koleksi Buku", en: "Book Collection" },
  "admin_collection_subtitle": { id: "Kelola data, stok, dan hapus buku", en: "Manage data, stock, and delete books" },
  "admin_manage_reviews": { id: "Kelola Ulasan", en: "Manage Reviews" },
  "admin_add_book": { id: "Tambah Buku", en: "Add Book" },
  "admin_th_book_info": { id: "Info Buku", en: "Book Info" },
  "admin_th_category": { id: "Kategori", en: "Category" },
  "admin_th_stock": { id: "Stok", en: "Stock" },
  "admin_th_action": { id: "Aksi", en: "Action" },
  "admin_loading_books": { id: "Memuat koleksi buku...", en: "Loading book collection..." },
  "admin_user_title": { id: "Data Mahasiswa & Admin", en: "Student & Admin Data" },
  "admin_user_subtitle": { id: "Kelola data dan berikan pangkat khusus", en: "Manage data and assign special roles" },
  "admin_set_role": { id: "Atur Pangkat", en: "Set Role" },
  "admin_th_fullname": { id: "Nama Lengkap", en: "Full Name" },
  "admin_th_email": { id: "Email", en: "Email" },
  "admin_th_role": { id: "Pangkat", en: "Role" },
  "admin_loading_users": { id: "Memuat data mahasiswa...", en: "Loading student data..." },
  "admin_set_role_title": { id: "Atur Pangkat Mahasiswa", en: "Set Student Role" },
  "admin_set_role_subtitle": { id: "Berikan wewenang pada user untuk mengelola perpustakaan.", en: "Grant authority to users to manage the library." },
  "admin_select_user": { id: "Pilih Mahasiswa", en: "Select Student" },
  "admin_select_role": { id: "Pilih Pangkat", en: "Select Role" },
  "btn_cancel": { id: "Batal", en: "Cancel" },
  "admin_save_role": { id: "Simpan Pangkat", en: "Save Role" },
  "admin_card_req_title": { id: "Request Buku", en: "Book Requests" },
  "admin_card_req_desc": { id: "Cek permintaan mahasiswa", en: "Check student requests" },
  "admin_card_manage_title": { id: "Manage Buku", en: "Manage Books" },
  "admin_card_manage_desc": { id: "Edit / Hapus koleksi", en: "Edit / Delete collection" },
  "admin_card_user_title": { id: "User Control", en: "User Control" },
  "admin_card_user_desc": { id: "Kelola data mahasiswa", en: "Manage student data" },
  "admin_edit_book_title": { id: "Update Koleksi Buku", en: "Update Book Collection" },
  "admin_edit_book_subtitle": { id: "Edit detail di sebelah kiri dan pantau perubahan kartu di sebelah kanan.", en: "Edit details on the left and monitor card changes on the right." },
  "admin_btn_save_changes": { id: "Simpan Perubahan", en: "Save Changes" },
  "borrow_status_available": { id: "Tersedia", en: "Available" },
  "book_detail_btn": { id: "Detail Buku", en: "Book Detail" },
  "admin_edit_comment": { id: "EDIT KOMENTAR", en: "EDIT COMMENT" },
  "admin_warn_limit": { id: "Telah melebihi limit (Maks 100 Karakter)!", en: "Exceeded limit (Max 100 Chars)!" },

  "admin_time_range": { id: "Rentang Waktu", en: "Time Range" },
  "admin_per_month": { id: "Per Bulan", en: "Per Month" },
  "admin_per_year": { id: "Per Tahun", en: "Per Year" },
  "admin_chart_books": { id: "Detail Koleksi Buku", en: "Book Collection Details" },
  "admin_chart_users": { id: "Detail Pertumbuhan Mahasiswa", en: "Student Growth Details" },
  "admin_chart_activity": { id: "Detail Log Aktivitas", en: "Activity Log Details" },
  "admin_chart_traffic": { id: "Detail Trafik Peminjaman", en: "Borrowing Traffic Details" },
  "admin_user_control_desc": { id: "Pantau daftar mahasiswa, cek pangkat, dan kelola akses akun.", en: "Monitor student list, check roles, and manage account access." },
  "admin_back_stats": { id: "Kembali ke Statistik", en: "Back to Statistics" },
  "admin_close_control": { id: "Tutup kontrol mahasiswa", en: "Close student control" },
  "admin_manage_book_desc": { id: "Kelola inventaris perpustakaan dan kelola ulasan.", en: "Manage library inventory and reviews." },
  "admin_close_collection": { id: "Tutup menu koleksi buku", en: "Close book collection menu" },
  "admin_request_desc": { id: "Tinjau semua permintaan yang sedang diajukan dan dipinjam.", en: "Review all pending and borrowed requests." },
  "admin_close_request": { id: "Tutup request list", en: "Close request list" },
  "admin_del_acc_title": { id: "Hapus Akun?", en: "Delete Account?" },
  "admin_del_acc_desc": { id: "Apakah kamu yakin ingin menghapus akun user ini? Data tidak bisa dikembalikan.", en: "Are you sure you want to delete this user's account? Data cannot be restored." },
  "btn_yes_delete": { id: "Ya, Hapus", en: "Yes, Delete" },
  "admin_deleting_acc": { id: "Menghapus Akun...", en: "Deleting Account..." },
  "admin_success": { id: "Berhasil", en: "Success" },
  "admin_del_acc_success": { id: "Akun user berhasil dihapus dari database.", en: "User account successfully deleted from database." },
  "admin_role_fail": { id: "Pangkat Gagal Disimpan", en: "Failed to Save Role" },
  "admin_role_success_title": { id: "Pangkat Berhasil Disimpan", en: "Role Successfully Saved" },
  "admin_role_success_desc": { id: "Pangkat user telah diperbarui.", en: "User role has been updated." },
  "admin_processing": { id: "Memproses...", en: "Processing..." },
  "admin_del_book_title": { id: "Hapus Buku?", en: "Delete Book?" },
  "admin_del_book_desc": { id: "Apakah kamu yakin ingin menghapus buku ini? Semua ulasan juga akan hilang.", en: "Are you sure you want to delete this book? All reviews will also be lost." },
  "admin_deleting_book": { id: "Menghapus Buku...", en: "Deleting Book..." },
  "admin_del_book_success": { id: "Buku berhasil dihapus.", en: "Book successfully deleted." },
  "admin_del_review_success_title": { id: "Ulasan Berhasil Dihapus", en: "Review Successfully Deleted" },
  "admin_del_review_success_desc": { id: "Komentar tersebut telah dihapus.", en: "The comment has been deleted." },
  "admin_del_review_fail": { id: "Ulasan Gagal Dihapus", en: "Failed to Delete Review" },
  "admin_edit_review_success": { id: "Komentar berhasil diperbarui.", en: "Comment successfully updated." },
  "admin_update_book_fail": { id: "Buku Gagal Diupdate", en: "Failed to Update Book" },
  "admin_update_book_success_title": { id: "Buku Berhasil Diupdate", en: "Book Successfully Updated" },
  "admin_update_book_success_desc": { id: "Data buku telah diperbarui di database.", en: "Book data updated in database." },
  "admin_err_process_req": { id: "Terjadi kesalahan saat memproses permintaan.", en: "An error occurred while processing the request." },
  "admin_warning": { id: "Peringatan", en: "Warning" },
  "admin_stock_empty": { id: "Stok tidak mencukupi untuk meminjamkan buku ini.", en: "Insufficient stock to lend this book." },
  "admin_req_approved": { id: "Buku telah disetujui.", en: "Book has been approved." },
  "admin_req_rejected": { id: "Buku telah ditolak.", en: "Book has been rejected." },
  "admin_req_returned": { id: "Buku telah dikembalikan.", en: "Book has been returned." },
  "borrow_status_pending": { id: "Menunggu Persetujuan", en: "Pending Approval" },
  "borrow_status_borrowed": { id: "Sedang Dipinjam", en: "Borrowed" },
  "admin_btn_approve": { id: "Setujui", en: "Approve" },
  "admin_btn_reject": { id: "Tolak", en: "Reject" },
  "admin_btn_return": { id: "Kembalikan", en: "Return" },
  "admin_btn_review": { id: "Ulasan", en: "Reviews" }
};

let file = 'c:/INFOKOM/PPLG/semester-2/april/web perpus/javascript/i18n.js';
let content = fs.readFileSync(file, 'utf8');


let enIndex = content.indexOf('  en: {');
let idPart = content.substring(0, enIndex);
let enPart = content.substring(enIndex);

let idInsert = '';
let enInsert = '';
for (let key in keysToAdd) {
  idInsert += `    "${key}": "${keysToAdd[key].id}",\n`;
  enInsert += `    "${key}": "${keysToAdd[key].en}",\n`;
}

idPart = idPart.replace(/  },\s*$/, `\n${idInsert}  },\n`);

enPart = enPart.replace(/  }\n};\s*$/, `\n${enInsert}  }\n};`);

fs.writeFileSync(file, idPart + enPart, 'utf8');
